const exactTranslations: Record<string, string> = {
    "Passed": "Aprovado",
    "Failed": "Reprovado",
    "Investigate": "Investigar",
    "Skipped": "Ignorado",
    "Planned": "Planejado",
    "Low": "Baixo",
    "Medium": "Médio",
    "High": "Alto",
    "N/A": "N/D",
    "Search by name...": "Buscar por nome...",
    "Risk:": "Risco:",
    "Status:": "Status:",
    "Filter by SFI Pillar:": "Filtrar por Pilar SFI (Secure Future Initiative):",
    "Clear All": "Limpar tudo",
    "Clear All Filters": "Limpar todos os filtros",
    "No results.": "Sem resultados.",
    "User Impact:": "Impacto ao usuário:",
    "Implementation Effort:": "Esforço de implementação:",
    "Test result →": "Resultado do teste →",
    "What was checked": "O que foi verificado",
    "No data available": "Sem dados disponíveis",
    "No description available": "Sem descrição disponível",
    "Last Scan": "Última verificação",
    "Tenant": "tenant",
    "Tenant ID": "ID do tenant",
    "Assessment generated by": "Avaliação gerada por",
    "Assessment run on": "Avaliação executada em",
    "Version": "Versão",
    "Resources": "Recursos",
    "Support": "Suporte",
    "Share Feedback": "Compartilhar feedback",
    "Report Issues": "Reportar problemas",
    "Privacy": "Privacidade",
    "Terms": "Termos",
    "Open": "Abrir",
    "Are you absolutely sure?": "Você tem absoluta certeza?",
    "This action cannot be undone. This will permanently delete your account and remove your data from our servers.": "Esta ação não pode ser desfeita. Ela removerá permanentemente sua conta e seus dados de nossos servidores.",
    "boosted by": "apoiado por",
    "Zero Trust Assessment": "Zero Trust Assessment",
    "Overview": "Visão geral",
    "Identity": "Identidade",
    "Devices": "Dispositivos",
    "Apps": "Aplicativos",
    "Network": "Rede",
    "Data": "Dados",
    "Infrastructure": "Infraestrutura",
    "Assessment": "Avaliação",
    "Steps": "Etapas",
    "Device sign-ins": "Entradas de dispositivos",
    "Mobile devices": "Dispositivos móveis",
    "Desktop devices": "Dispositivos desktop",
    "Compliant": "Em conformidade",
    "Non-compliant": "Não conforme",
    "Unmanaged": "Não gerenciado",
    "Managed": "Gerenciado",
    "User sign in": "Entrada de usuário",
    "Users": "Usuários",
    "Single factor": "Fator único",
    "Phishable": "Suscetível a phishing",
    "Phone": "Telefone",
    "Authenticator": "Autenticador",
    "Phish resistant": "Resistente a phishing",
    "Passkey": "Chave de acesso",
    "WHfB": "WHfB",
    "No CA applied": "Nenhuma CA aplicada",
    "CA applied": "CA aplicada",
    "No MFA": "Sem MFA",
    "MFA": "MFA",
    "Entra joined": "Ingressado no Entra",
    "Entra hybrid joined": "Ingresso híbrido no Entra",
    "Entra registered": "Registrado no Entra",
    "Android": "Android",
    "iOS": "iOS",
    "Android (Company)": "Android (Corporativo)",
    "Android (Personal)": "Android (Pessoal)",
    "iOS (Company)": "iOS (Corporativo)",
    "iOS (Personal)": "iOS (Pessoal)",
    "Corporate": "Corporativo",
    "Personal": "Pessoal",
    "Selected": "Selecionado",
    "All active users": "Todos os usuários ativos",
    "Not Applicable": "Não aplicável",
    "Blocked": "Bloqueado",
    "Allowed": "Permitido",
    "Default": "Padrão",
    "Immediately": "Imediatamente",
    "Yes": "Sim",
    "No": "Não",
    "Clear": "Limpo",
    "Secured": "Protegido",
    "Alphanumeric": "Alfanumérico",
    "All devices": "Todos os dispositivos",
    "All users": "Todos os usuários",
    "Specific Groups": "Grupos específicos",
    "Protect tenants and isolate production systems": "Proteger tenants e isolar sistemas de produção",
    "Monitor and detect": "Monitorar e detectar",
    "Protect engineering": "Proteger a engenharia",
    "Protect identities": "Proteger identidades",
    "Protect tenants": "Proteger tenants",
    "Accelerate response": "Acelerar a resposta",
}

export function translateText(value: string | number | boolean | null | undefined): string {
    if (value === null || value === undefined || value === "") {
        return "N/D";
    }

    if (typeof value === "boolean") {
        return value ? "Sim" : "Não";
    }

    const text = String(value);
    return exactTranslations[text] ?? text;
}

export function translateSfiPillar(value: string | null | undefined): string {
    return translateText(value);
}

export function translateStatusLabel(value: string | null | undefined): string {
    return translateText(value);
}

export function translateSankeyLabel(value: string): string {
    return exactTranslations[value] ?? value;
}
